stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  image: docker:latest
  variables:
    AWS_DEFAULT_REGION: us-east-2
    # NO "://" and MUST include your Account ID
    ECR_REGISTRY: 589535355002.dkr.ecr.us-east-2.amazonaws.com
    ECR_REPO: 589535355002.dkr.ecr.us-east-2.amazonaws.com/tracker-app
    # This prevents the "extra" 0.00MB metadata files in ECR
    DOCKER_DEFAULT_PLATFORM: linux/amd64
  before_script:
    - apk add --no-cache aws-cli
    - export TIMESTAMP=$(date +%Y%m%d-%H%M)
    - export UNIQUE_TAG="${CI_COMMIT_REF_SLUG}-${TIMESTAMP}"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    # This logs into the specific AWS registry
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    # Use --provenance=false to keep ECR clean (only 1 image row)
    - docker build --provenance=false -t tracker-app .
    - docker tag tracker-app:latest $ECR_REPO:$UNIQUE_TAG
    - docker push $ECR_REPO:$UNIQUE_TAG
  only:
    - main
