stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  image: docker:latest
  variables:
    AWS_DEFAULT_REGION: us-east-2
    ECR_REPO: ://amazonaws.com
  before_script:
    - apk add --no-cache aws-cli
    # Generate a timestamp (YearMonthDay-HourMinute)
    - export TIMESTAMP=$(date +%Y%m%d-%H%M)
    # Combine branch name and timestamp for a unique tag
    - export UNIQUE_TAG="${CI_COMMIT_REF_SLUG}-${TIMESTAMP}"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  script:
    - docker build -t tracker-app .
    # Tag with the unique timestamp
    - docker tag tracker-app:latest $ECR_REPO:$UNIQUE_TAG
    # Push ONLY this unique tag
    - docker push $ECR_REPO:$UNIQUE_TAG
  only:
    - main
